language: scala
jdk: openjdk8
scala:
  - 2.11.12
   
# TODO 将CI触发限定在duckling-fork-chinese目录中

script:
  # 加载sbt-launch有可能失败
  - mkdir -p /home/travis/.sbt/launchers/1.5.0
  - wget https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.5.0/sbt-launch-1.5.0.jar -O /home/travis/.sbt/launchers/1.5.0/sbt-launch.jar
  - cd duckling-fork-chinese
  - sbt clean coverage test
  - sbt coverageAggregate
after_success:
  - bash <(curl -s https://codecov.io/bash)
