name: "Release of Duckling"
on:
  push:
    branches: [master, main]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - run: sbt ci-release
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}